#include "Events.h"

char* EventsNames[14] = 
{
	"FORWARD_WALK",
	"BACK_WALK",
	"LEFT_WALK",
	"RIGHT_WALK",
	"MOUSE_MOVED",
	"PRIMARY_ATTACK",
	"SECONDARY_ATTACK",
	"LEFT_CLICK",
	"RIGHT_CLICK",
	"MIDDLE_CLICK",
	"SPELL_SELECT_UP",
	"SPELL_SELECT_DOWN",
	"UNKNOWN_EVENT",
	"NUM_EVENTS"
};
