
//Player 1
#define P1_FORWARD_WALK_PRESS 0
#define P1_FORWARD_WALK_RELEASE 1
#define P1_BACK_WALK_PRESS 2
#define P1_BACK_WALK_RELEASE 3
#define P1_LEFT_WALK_PRESS 4
#define P1_LEFT_WALK_RELEASE 5
#define P1_RIGHT_WALK_PRESS 6
#define P1_RIGHT_WALK_RELEASE 7

//Player 2
#define P2_FORWARD_WALK_PRESS 8
#define P2_FORWARD_WALK_RELEASE 9
#define P2_BACK_WALK_PRESS 10
#define P2_BACK_WALK_RELEASE 11
#define P2_LEFT_WALK_PRESS 12
#define P2_LEFT_WALK_RELEASE 13
#define P2_RIGHT_WALK_PRESS 14
#define P2_RIGHT_WALK_RELEASE 15

// Player 3
#define P3_FORWARD_WALK_PRESS 16
#define P3_FORWARD_WALK_RELEASE 17
#define P3_BACK_WALK_PRESS 18
#define P3_BACK_WALK_RELEASE 19
#define P3_LEFT_WALK_PRESS 20
#define P3_LEFT_WALK_RELEASE 21
#define P3_RIGHT_WALK_PRESS 22
#define P3_RIGHT_WALK_RELEASE 23

// Player 4
#define P4_FORWARD_WALK_PRESS 24
#define P4_FORWARD_WALK_RELEASE 25
#define P4_BACK_WALK_PRESS 26
#define P4_BACK_WALK_RELEASE 27
#define P4_LEFT_WALK_PRESS 28
#define P4_LEFT_WALK_RELEASE 29
#define P4_RIGHT_WALK_PRESS 30
#define P4_RIGHT_WALK_RELEASE 31
#define NUM_EVENTS 32
